#!/bin/bash


if [[ ! -d "/workspaces/dev-container" ]]; then
    echo "This script should only be used from within the dev-container."
elif [ -z "$1" ]; then
    echo "Please provide a unique identifier for the image."
else
    docker build /workspaces/dev-container/SagemakerTemplate -t "432722299252.dkr.ecr.us-east-1.amazonaws.com/sagemaker:$1" --build-arg CACHE_DATE=$(date +%Y-%m-%d:%H:%M:%S)

    docker push "432722299252.dkr.ecr.us-east-1.amazonaws.com/sagemaker:$1"
fi