#!/bin/bash

if [[ ! -d "/workspaces/dev-container" ]]; then
    echo "This script should only be used from within the dev-container."
else
    docker push 432722299252.dkr.ecr.us-east-1.amazonaws.com/sagemaker:latest
fi